name: XUnit Tests

on:
  push:
    branches: [ test ]

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      
      - name: Run Xunit tests
        run: dotnet test ${{ github.workspace }}/src/jwtPS/jwtPSTest/jwtPSTest.csproj --verbosity normal