name: XUnit Tests

on:
  push:
    branches: [ test ]

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build the module
        run: dotnet build ${{ github.workspace }}/src/jwtPS/jwtPS.csproj
      
      - name: Run Xunit tests
        run: dotnet test ${{ github.workspace }}/src/jwtPSTest/jwtPSTest.csproj --verbosity normal